# Generated by Django 3.1.5 on 2021-01-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('roll_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
